<script setup lang="ts">
import { ref } from 'vue'

const isAnimated = ref(false)
const isMouseStayOver = ref(false)

const animationDuration = 800 // 8s

function animate() {
  if (isAnimated.value) {
    return
  }
  isAnimated.value = true
  setTimeout(() => {
    isAnimated.value = false
  }, animationDuration)
}

function onMouseOver() {
  if (isMouseStayOver.value) {
    return
  }
  isMouseStayOver.value = true
  animate()
}
</script>

<template>
  <div
    class="title"
    :class="[isAnimated ? 'title-animated' : '']"
    @click="animate"
    @mouseover="onMouseOver"
    @mouseleave="isMouseStayOver = false"
  >
    <span>Nelly</span>
    <span class="last-name">Mure</span>
  </div>
</template>

<style scoped>
.title {
  display: flex;
  flex-direction: row;
  color: var(--color-hex-black-orange);
  font-family: var(--font-family-le-murmure);
  font-weight: var(--font-weight-normal);
  line-height: 1;
}
.title-animated {
  animation: jello-diagonal-2 0.8s both;
}
.last-name {
  margin-top: 0.5em;
  margin-left: 0.1em;
  align-self: flex-end;
}
/* ----------------------------------------------
 * Generated by Animista on 2025-7-20 11:28:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes jello-diagonal-2 {
  0% {
    -webkit-transform: skew(0deg 0deg);
    transform: skew(0deg 0deg);
  }
  30% {
    -webkit-transform: skew(-25deg -25deg);
    transform: skew(-25deg -25deg);
  }
  40% {
    -webkit-transform: skew(15deg, 15deg);
    transform: skew(15deg, 15deg);
  }
  50% {
    -webkit-transform: skew(-15deg, -15deg);
    transform: skew(-15deg, -15deg);
  }
  65% {
    -webkit-transform: skew(5deg, 5deg);
    transform: skew(5deg, 5deg);
  }
  75% {
    -webkit-transform: skew(-5deg, -5deg);
    transform: skew(-5deg, -5deg);
  }
  100% {
    -webkit-transform: skew(0deg 0deg);
    transform: skew(0deg 0deg);
  }
}
</style>
